coverage:
  status:
    project:
      default:
        target: 70
        threshold: 10
        base: auto
        paths:
          - "src"
    patch:
      default:
        target: 70
        paths:
          - "src"
