name: Conda build

on:
  push:
    branches: ["main"]
    paths: ["**.py", "environment.yml"]
  pull_request:
    branches: ["main"]
    paths: ["**.py", "environment.yml"]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Conda environment
        uses: actions/cache@v3
        with:
          path: ~/.conda/pkgs
          key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}
          restore-keys: conda-${{ runner.os }}-

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base

      - name: Lint with flake8
        run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=130 --statistics

      - name: Install package
        run: |
          pip install .

      - name: Cache external data
        uses: actions/cache@v3
        with:
          path: ~/.dbcanlight
          key: dbcanlight-external

      - name: Get external data
        run: |
          mkdir -p ~/.dbcanlight
          curl -o ~/.dbcanlight/substrate_mapping.tsv https://bcb.unl.edu/dbCAN2/download/Databases/fam-substrate-mapping-08252022.tsv
          curl -o ~/.dbcanlight/cazyme.hmm https://bcb.unl.edu/dbCAN2/download/Databases/V12/dbCAN-HMMdb-V12.txt
          curl -o ~/.dbcanlight/substrate.hmm https://bcb.unl.edu/dbCAN2/download/Databases/dbCAN_sub.hmm

      - name: Test with pytest
        run: |
          conda install pytest
          pytest
