name: Download database files

on: workflow_call

jobs:
  build_diamond:
    name: Download database files
    runs-on: ubuntu-latest

    steps:
      - name: Cache database files
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.dbcanlight/cazyme.hmm
            ~/.dbcanlight/substrate_mapping.tsv
            ~/.dbcanlight/substrate.hmm
            ~/.dbcanlight/cazydb.dmnd
          key: dbcanlight-databases

      - name: Cache diamond
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.local/bin/diamond
          key: ${{ runner.os }}-diamond

      - name: Download diamond executable
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.dbcanlight
          curl -o ~/.dbcanlight/cazyme.hmm https://bcb.unl.edu/dbCAN2/download/Databases/V12/dbCAN-HMMdb-V12.txt
          curl -o ~/.dbcanlight/substrate_mapping.tsv https://bcb.unl.edu/dbCAN2/download/Databases/fam-substrate-mapping-08252022.tsv
          curl -o ~/.dbcanlight/substrate.hmm https://bcb.unl.edu/dbCAN2/download/Databases/dbCAN_sub.hmm
          curl -o ~/.dbcanlight/cazydb.fa https://bcb.unl.edu/dbCAN2/download/Databases/CAZyDB.07262023.fa
          diamond makedb --in ~/.dbcanlight/cazydb.fa --db ~/.dbcanlight/cazydb.dmnd -t 4
