name: CD/release
run-name: Release - v${{ github.event.client_payload.version }}

on:
  repository_dispatch:
    types: [release]

jobs:
  build-and-test:
    uses: ./.github/workflows/build_and_test.yml

  publish_release:
    name: Publish release
    environment: GitHub releases
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Restore cache to CHANGELOG.md and CITATION.cff
        uses: actions/cache/restore@v4
        with:
          path: |
            CHANGELOG.md
            CITATION.cff
          key: version-bump-v${{ github.event.client_payload.version }}-${{ github.event.client_payload.run_id }}

      - name: Get release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: latest

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Release v${{ github.event.client_payload.version }}"

      - name: Push changes
        run: git push

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.query-release-info.outputs.release-notes }}
          tag_name: v${{ github.event.client_payload.version }}
          prerelease: ${{ github.event.client_payload.bump_type == 'prerelease' }}
          make_latest: ${{ github.event.client_payload.bump_type != 'prerelease' }}
